title = "Linux Day Messina 2024"
base_url = "https://linuxday.messina.it"

theme = "linux-day"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
event_date = "Sabato 26 ottobre"
event_year = "2024"
event_location = "Dipartimento di Ingegneria"
event_location_extra = "Aula Magna"

eventbrite_url = "https://www.eventbrite.com/e/linux-day-2024-tickets-1051924503507"
