title = "Linux Day Messina 2024"
base_url = "https://linuxday.messina.it"

theme = "linux-day"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]

[extra.event]
date = "Sabato 26 ottobre"
year = "2024"
location = "Dipartimento di Ingegneria"
location_extra = "Aula Magna"
eventbrite_url = "https://www.eventbrite.com/e/linux-day-2024-tickets-1051924503507"

[extra.meta]
description = "Giornata nazionale del software libero e delle libertà digitali. Sabato 26 ottobre al Dipartimento di Ingegneria"
keywords = "linux, linux day, messina, 2024, free software, software libero, libertà digitali, unime, ingegneria"
