[intro]
time = "9:00"
title = "Registrazione partecipanti e saluti introduttivi"

[lunch]
time = "13:00"
title = "Pausa pranzo"

[[talks]]
time = "9:30"
title = "DiscCheckEmu: un nuovo approccio open source al cracking dei software legacy"
author = "Luca D'Amico"

[[talks]]
time = "10:00"
title = "Deployment riproducibili con Nix e NixOS"
author = "Tancredi Orlando"

[[talks]]
time = "10:30"
title = "Cosa k8s sono i container?"
author = "Alberto Pimpo"

[[talks]]
time = "11:00"
title = "Il codice che scriviamo è sicuro? Strumenti SAST (Static Application Security Testing)"
author = "Salvatore Todaro"

[[talks]]
time = "11:30"
title = "Da Zero a Git: Le Basi per la Collaborazione"
author = "Antonio Battaglia"

[[talks]]
time = "12:00"
title = "Offensive Solitaire, attacco e difesa su GNU/Linux"
author = "Fabio Genovese"

[[talks]]
time = "12:30"
title = "Gaming su Linux: Steam Proton"
author = "Vincenzo Bucaria"

[[workshops]]
time = "15:00"
title = "Linux Install Fest"
author = "MetaGriPwn HackLab"
room = "Aula 421"

[[workshops]]
time = "15:00"
title = "Come k8s si usano i container?"
author = "Alberto Pimpo"
room = "Aula 422"

[[workshops]]
time = "15:00"
title = "L'editor di testo Vim"
author = "Michele Arena"
room = "Aula 423"

[[workshops]]
time = "15:00"
title = "LLM open source"
author = "Gaetano Pispisa"
room = "Aula 424"
