[intro]
time = "9:00"
title = "Registrazione partecipanti e saluti introduttivi"

[lunch]
time = "13:00"
title = "Pausa pranzo"

[[talks]]
time = "TBD"
title = "TBD"
author = "TBD"

[[workshops]]
time = "TBD"
title = "TBD"
author = "TBD"
room = "TBD"
